os: linux
dist: xenial
sudo: false

language: java
jdk:
  - openjdk8
  - openjdk11

install: true
before_script: mvn clean
script: mvn -P jacoco-agent test
after_success:
  - mvn -P jacoco jacoco:report
  - mvn -P coveralls coveralls:report