version: '3'

services:
  build:
    image: maven:3-jdk-11-slim
    container_name: system-monitor-build
    working_dir: /root/system-monitor/
    command: "mvn -T C1 clean package"
    volumes:
      - .:/root/system-monitor/:delegated

  server:
    image: openjdk:11-jre-slim
    container_name: system-monitor-server
    command: "/opt/system-monitor/system-monitor"
    ports:
      - "5005:5005"
    volumes:
      - ./modules/server/target/server.jar:/opt/system-monitor/system-monitor:ro
      - ./modules/server/docker/server.conf:/opt/system-monitor/system-monitor.conf:ro

  web:
    image: openjdk:11-jre-slim
    container_name: system-monitor-web
    command: "/opt/system-monitor/system-monitor"
    depends_on:
      - server
    ports:
      - "8080:8080"
    volumes:
      - ./modules/web/target/web.jar:/opt/system-monitor/system-monitor:ro
      - ./modules/web/docker/web.conf:/opt/system-monitor/system-monitor.conf:ro
      - ./modules/web/docker/web.yml:/opt/system-monitor/config/application.yml:ro