spring:
  jmx:
    enabled: false
monitor:
  period: 3
sensors:
  cpu:
    file: /proc/stat
  mem:
    file: /proc/meminfo
  disk:
    file: /proc/diskstats
    sector: 512
  net:
    file: /proc/net/dev