spring:
  jmx:
    enabled: false
monitor:
  period: 3
directory:
  proc: /proc
sensors:
  cpu:
    file: ${directory.proc}/stat
  mem:
    file: ${directory.proc}/meminfo
  disk:
    file: ${directory.proc}/diskstats
    sector: 512
  net:
    file: ${directory.proc}/net/dev